sudo: required
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7

services:
  - redis-server

env:
  global:
    - BRANCH=master
  matrix:
    - DB=mysql

matrix:
  include:
    - php: 5.4
      env: DB=sqlite
    - php: 5.4
      env: DB=pgsql
    - php: 5.6
      env: DB=mysql BRANCH=stable8
    - php: 5.6
      env: DB=mysql BRANCH=stable8.1
    - php: 5.6
      env: DB=mysql BRANCH=stable8.2


install: ./tests/travis/install-$BRANCH.sh

# Note the install script should make sure we are in the apps/ojsxc directory
script:
  - composer install
  - phpunit -c phpunit.xml
  - phpunit -c phpunit.integration.xml
  - cat ../../data/owncloud.log
